[project]
name = "llm-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zephaniah Darden", email = "86165493+dev-vader091@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ollama>=0.6.2",
]

[project.scripts]
llm-lab = "llm_lab:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
